Repository meshery/meshery-kuma, pull requests merged in 2022-10, with the labels that each got.

#329 Update multi-platform workflow with correct build args
  .github/workflows/multi-platform.yml
Labels: hacktoberfest, area/ci

#322 [Chore] Golang update to 1.19
  .github/workflows/build-and-release.yml
  .github/workflows/ci.yml
  .github/workflows/e2etest.yaml
  .github/workflows/error-ref-publisher.yml
  .github/workflows/multi-platform.yml
  .golangci.yaml
  Dockerfile
  Makefile
  build/Makefile.core.mk
  build/config.go
  go.mod
  go.sum
  internal/config/config.go
  internal/config/operations.go
  kuma/error.go
  kuma/install.go
  kuma/kuma.go
  kuma/oam.go
  main.go
Labels: kind/chore, language/go

#333 Added components to doc workflow
  .github/workflows/components-to-doc.yml
Labels: area/docs, area/tests, area/ci
